### ISSUE TITLE
Error 403 Forbidden

### ISSUE THREAD

**Issue by Esv256** [rhomeister/firepi#3]
Hi, 

I don't if you're still working on this project. Hoping you could help me out with the errors i'm getting after install. To me it looks like a token issue. When I use the API token from /home/pi/firepi-master/.local_settings.ini in a webbrowser i get a succesfull login. https://www.brandweerrooster.nl/users/current.json?auth_token=*************

sudo python firepi

Please select the system you use
1. FireServiceRota (international)
2. Brandweerrooster (Netherlands)
Please enter 1 or 2: 2
Please enter your email address: ******@******.nl
Please enter your password: 
Logged in

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/firepi-master/firepi/__main__.py", line 54, in <module>
    main()
  File "/home/pi/firepi-master/firepi/__main__.py", line 34, in main
    main = Main()
  File "/home/pi/firepi-master/firepi/__main__.py", line 13, in __init__
    self.availability_api = AvailabilityAPI(API_KEY)
  File "firepi/availability_api.py", line 10, in __init__
    self.user_id = UserAPI(token).current()['id']
  File "firepi/user_api.py", line 11, in current
    return json.load(urllib2.urlopen(url))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

**Comment by rhomeister** [comment]
Hi @Esv256. This project is not being maintained anymore. We have a completely new API, and this project uses the old deprecated one. You can find the details of the new API here: https://www.brandweerrooster.nl/apidocs/.

Depending on what you intend to use this for, you might also be interested in https://github.com/cyberjunky/home-assistant-fireservicerota, which is a project by a Brandweerrooster user to integrate alerting into home automation. He will give a talk at the Home Assistant Conference about this on the 13th of December I believe.

**Comment by Esv256** [comment]
Hi i installed the HA plugin before i found out about this project. Wasn't sure how quick the alert would show up in HA, so wanted to test this as well. I had to wait for a alarm to test the HA plugin and turned out to be 9 sec faster then my pager, fast enough to turn on my lights at night!

Thanks for your reply!

**Comment by rhomeister** [comment]
You're very welcome. Let me know if there is anything else we can do for
you.

BTW, the reason the home assistant plugin is faster, is that it uses our
real-time websockets API instead of polling our REST API. So that's another
benefit ;)
